<?php /* @var $block \Airslamit\Gcr\Block\Success */?>

<!-- BEGIN GCR Opt-in Module Code -->
<script src="https://apis.google.com/js/platform.js?onload=renderOptIn"
  async defer>
</script>

<script>
  window.renderOptIn = function() { 
    window.gapi.load('surveyoptin', function() {
      window.gapi.surveyoptin.render(
        {
          // REQUIRED
          "merchant_id": "<?php echo $block->getConfigMerchantId(); ?>",
          "order_id": "<?php echo $block->getOrderId(); ?>",
          "email": "<?php echo $block->getOrder()->getCustomerEmail(); ?>",
          "delivery_country": "<?php echo $block->getConfigCountry(); ?>",
          "estimated_delivery_date": "<?php echo $block->getEstimatedDate(); ?>",

          // OPTIONAL
          "opt_in_style": "<?php echo $block->getConfigOptInStyle(); ?>",
          "products": <?php print_r($block->getGtinProducts()); ?>
        }); 
     });
  }
</script>
<!-- END GCR Opt-in Module Code -->

<!-- BEGIN GCR Language Code -->
<script>
  window.___gcfg = {
    lang: "<?php echo $block->getLanguageCode(); ?>"
  };
</script>
<!-- END GCR Language Code -->